name: 'CI'

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  terraform:
    name: 'ci'
    runs-on: ubuntu-latest



    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout


